import dayjs from 'dayjs';

export const routes = {
  home: '/',
  explore: '/feed/explore',
  subscriptions: '/feed/subscriptions',
  library: '/feed/library',
};

export const mockVideos = [
  {
    title: 'Best of Mythic Quest',
    channel: { name: 'Sitcom Radio', id: 1234 },
    views: 4290,
    url: 'http://unsplash.it/250/150?gravity=center&page=1',
    id: 'abdefghijk',
    uploadDatetime: dayjs(),
  },
  {
    title: 'Best of Mythic Quest',
    channel: { name: 'Sitcom Radio', id: 1234 },
    views: 4290,
    url: 'http://unsplash.it/250/150?gravity=center&page=1',
    id: 'abdefghijk',
    uploadDatetime: dayjs(),
  },
  {
    title: 'Best of Mythic Quest',
    channel: { name: 'Sitcom Radio', id: 1234 },
    views: 4290,
    url: 'http://unsplash.it/250/150?gravity=center&page=1',
    id: 'abdefghijk',
    uploadDatetime: dayjs(),
  },
  {
    title: 'Best of Mythic Quest',
    channel: { name: 'Sitcom Radio', id: 1234 },
    views: 4290,
    url: 'http://unsplash.it/250/150?gravity=center&page=1',
    id: 'abdefghijk',
    uploadDatetime: dayjs(),
  },
  {
    title: 'Best of Mythic Quest',
    channel: { name: 'Sitcom Radio', id: 1234 },
    views: 4290,
    url: 'http://unsplash.it/250/150?gravity=center&page=1',
    id: 'abdefghijk',
    uploadDatetime: dayjs(),
  },
  {
    title: 'Best of Mythic Quest',
    channel: { name: 'Sitcom Radio', id: 1234 },
    views: 4290,
    url: 'http://unsplash.it/250/150?gravity=center&page=1',
    id: 'abdefghijk',
    uploadDatetime: dayjs(),
  },
  {
    title: 'Best of Mythic Quest',
    channel: { name: 'Sitcom Radio', id: 1234 },
    views: 4290,
    url: 'http://unsplash.it/250/150?gravity=center&page=1',
    id: 'abdefghijk',
    uploadDatetime: dayjs(),
  },
  {
    title: 'Best of Mythic Quest',
    channel: { name: 'Sitcom Radio', id: 1234 },
    views: 4290,
    url: 'http://unsplash.it/250/150?gravity=center&page=1',
    id: 'abdefghijk',
    uploadDatetime: dayjs(),
  },
  {
    title: 'Best of Mythic Quest',
    channel: { name: 'Sitcom Radio', id: 1234 },
    views: 4290,
    url: 'http://unsplash.it/250/150?gravity=center&page=1',
    id: 'abdefghijk',
    uploadDatetime: dayjs(),
  },
  {
    title: 'Best of Mythic Quest',
    channel: { name: 'Sitcom Radio', id: 1234 },
    views: 4290,
    url: 'http://unsplash.it/250/150?gravity=center&page=1',
    id: 'abdefghijk',
    uploadDatetime: dayjs(),
  },
  {
    title: 'Best of Mythic Quest',
    channel: { name: 'Sitcom Radio', id: 1234 },
    views: 4290,
    url: 'http://unsplash.it/250/150?gravity=center&page=1',
    id: 'abdefghijk',
    uploadDatetime: dayjs(),
  },
  {
    title: 'Best of Mythic Quest',
    channel: { name: 'Sitcom Radio', id: 1234 },
    views: 4290,
    url: 'http://unsplash.it/250/150?gravity=center&page=1',
    id: 'abdefghijk',
    uploadDatetime: dayjs(),
  },
  {
    title: 'Best of Mythic Quest',
    channel: { name: 'Sitcom Radio', id: 1234 },
    views: 4290,
    url: 'http://unsplash.it/250/150?gravity=center&page=1',
    id: 'abdefghijk',
    uploadDatetime: dayjs(),
  },
  {
    title: 'Best of Mythic Quest',
    channel: { name: 'Sitcom Radio', id: 1234 },
    views: 4290,
    url: 'http://unsplash.it/250/150?gravity=center&page=1',
    id: 'abdefghijk',
    uploadDatetime: dayjs(),
  },
  {
    title: 'Best of Mythic Quest',
    channel: { name: 'Sitcom Radio', id: 1234 },
    views: 4290,
    url: 'http://unsplash.it/250/150?gravity=center&page=1',
    id: 'abdefghijk',
    uploadDatetime: dayjs(),
  },
  {
    title: 'Best of Mythic Quest',
    channel: { name: 'Sitcom Radio', id: 1234 },
    views: 4290,
    url: 'http://unsplash.it/250/150?gravity=center&page=1',
    id: 'abdefghijk',
    uploadDatetime: dayjs(),
  },
];
